### ISSUE TITLE
GUI crashes with `buffer not divisible by scale (2)`

### ISSUE THREAD

**Issue by aslpavel** [Umio-Yasuno/amdgpu_top#71] opened 2024-02-05 19:40 UTC
When scaling is used (in my case 2) under wayland GUI crashes with:
```
$ RUST_BACKTRACE=1 amdgpu_top --gui
wl_surface@24: error 2: Buffer size (359x465) is not divisible by scale (2)
Protocol error 2 on object wl_surface@24: 
Protocol error 2 on object wl_surface@24: 
Protocol error 2 on object wl_surface@24: 
Failed to set up a graphics context (OpenGL).
winit EventLoopError: Exit Failure: 1
thread 'main' panicked at crates/amdgpu_top_gui/src/lib.rs:274:9:
explicit panic
stack backtrace:
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```
`--list` output:
```
$ amdgpu_top --list
amdgpu_top v0.7.0

#0:
    AMD Radeon Graphics (0x15BF.0xC4)
    DevicePath { render: "/dev/dri/renderD128", card: "/dev/dri/card1", pci: "0000:c1:00.0" }
```
Window manager is Sway. If scaling is set to 1 it starts fine.

**Comment by Umio-Yasuno** [comment] 2024-02-06 22:25
I couldn't reproduce the issue in my environment.  
I found a similar issue reported in `winit` crate, but it should have been fixed in 0.29.9.

https://github.com/alacritty/alacritty/issues/7559

**Comment by Umio-Yasuno** [comment] 2024-02-10 02:09
Could you please attach the sway version and config file?  
The error is occurring on the sway (wlroots) side.

**Comment by aslpavel** [comment] 2024-02-10 12:47
I think this issue to introduction of this event to the wayland protocol [preferred_buffer_scale](https://gitlab.freedesktop.org/wayland/wayland/-/merge_requests/220).

My config at least related part are:
```
output eDP-1 {
    scale 1.5
    pos 0 0 res 2256x1504
}
```
And sway version is `1.8.1` operating system is Archlinux.
I have also build `amdgpu_top` from git master, and it is reproducible there.

**Comment by aslpavel** [comment] 2024-02-10 12:54
Here is also a full log of crash with wayland debug and rust backtrace enabled: 
[amdgpu_top_waland_debug.txt](https://github.com/Umio-Yasuno/amdgpu_top/files/14229291/amdgpu_top_waland_debug.txt)

**Comment by Umio-Yasuno** [comment] 2024-02-10 14:23
I couldn't reproduce it with `sway-1.8.1` and `wlroots-0.16.2`.  
As `amdgpu_top` does not directly handle the wayland protocol, it is assumed to be the problem with the crate used by `amdgpu_top` or with the wayland compositor.  
Sorry, there's nothing I can do.

**Closed by Umio-Yasuno** 2024-02-10 14:23 UTC
